### ISSUE TITLE
error when I tried this code in linux...

### ISSUE THREAD

**Issue by teddykspark** [dnouri/cuda-convnet#6]
When I replaced the codes in layer.py like the below...        

```
    dic, name = self.dic, self.dic['name']
    dic['dropout'] = 0.0
    if name in mcp.sections():
        dic['dropout'] = mcp.safe_get_float(name, 'dropout', default=0.0)
```

it shown the error message which's about the 'name' in dic is not defined..
well, I changed the codes in layer.cu, layer.cuh, convert.cu, layer.py after comparing files with the original cuda-convnet codes.

How to solve this issues? please give me the tips..

**Comment by WytheZ** [comment]
@teddykspark , can you give me some details of how you deal with the cuda 4.0? My cuda version is cuda 4.2.. Thanks!!
